export const dictionaries = {
  en: {
    nav: {
      buy: "Buy",
      rent: "Rent",
      agents: "Agents",
      offices: "Offices",
      about: "About",
      contact: "Contact",
      listProperty: "List Property",
      adminLogin: "Admin",
    },
    hero: {
      badge: "Albania's #1 Real Estate Platform",
      title1: "Find the place where your",
      title2: "story begins",
      subtitle: "Explore thousands of carefully curated homes, apartments and investment properties across Albania's most desirable locations.",
      search: "Search",
      buy: "Buy",
      rent: "Rent",
      anyType: "Any type",
      maxPrice: "Max price (EUR)",
      location: "City or neighborhood",
      stats: {
        listings: "Active Listings",
        agents: "Expert Agents",
        offices: "Offices",
        clients: "Happy Clients",
      },
    },
    home: {
      destinationsLabel: "Explore",
      destinationsTitle: "Destinations across Albania",
      allProperties: "All properties",
      featuredLabel: "Handpicked",
      featuredTitle: "Featured Properties",
      featuredSub: "Premium listings selected by our senior brokers.",
      viewAll: "View all",
      whyLabel: "Why Brunes",
      whyTitle: "The trusted partner for your property journey",
      why: {
        verified: { t: "Verified Listings", d: "Every property vetted by our compliance team." },
        experts: { t: "Expert Agents", d: "440+ licensed professionals across 47 offices." },
        awards: { t: "Award Winning", d: "Best real estate network in Albania 2023 & 2024." },
        reach: { t: "Nationwide Reach", d: "From coastal resorts to capital downtown." },
      },
      agentsLabel: "Team 21",
      agentsTitle: "Meet our top agents",
      allAgents: "All agents",
      ctaTitle: "Ready to list your property?",
      ctaSub: "Reach thousands of serious buyers. Free valuation, premium placement, expert guidance.",
      ctaPrimary: "List for Free",
      ctaSecondary: "Talk to an expert",
      testimonials: [
        { name: "Arta M.", role: "Bought a villa in Sarandë", quote: "The Brunes team guided us through every step. Found our dream beachfront villa in under a month." },
        { name: "Luca R.", role: "Relocated from Italy", quote: "Professional, multilingual, and incredibly responsive. Couldn't imagine moving to Albania without them." },
        { name: "Gent B.", role: "Property investor", quote: "Detailed market analysis, verified listings, and strong negotiation. My go-to agency for every deal." },
      ],
      propsIn: "properties",
    },
    properties: {
      title: "Properties",
      results: "results",
      showing: "Showing",
      of: "of",
      noResults: "No properties found",
      noResultsSub: "Try adjusting your filters.",
      sort: {
        newest: "Newest",
        priceAsc: "Price: Low to High",
        priceDesc: "Price: High to Low",
        areaDesc: "Largest first",
      },
      filters: {
        title: "Filters",
        clear: "Clear",
        all: "All",
        buy: "Buy",
        rent: "Rent",
        type: "Property Type",
        any: "Any",
        city: "City",
        allCities: "All cities",
        priceRange: "Price Range (EUR)",
        min: "Min",
        max: "Max",
        rooms: "Rooms",
        apply: "Apply Filters",
      },
    },
    propertyCard: {
      featured: "Featured",
      forSale: "For Sale",
      forRent: "For Rent",
    },
    propertyDetail: {
      forSale: "For Sale",
      forRent: "For Rent",
      save: "Save",
      share: "Share",
      about: "About this property",
      amenities: "Amenities",
      location: "Location",
      similar: "Similar properties",
      views: "views",
      specs: {
        rooms: "Rooms",
        baths: "Baths",
        area: "Area",
        floor: "Floor",
        year: "Year",
      },
      breadcrumb: { home: "Home", properties: "Properties" },
    },
    contact: {
      formTitle: "Contact Agent",
      name: "Your name",
      email: "Email",
      phone: "Phone (optional)",
      defaultMessage: "Hi, I'm interested in this property and would like to schedule a viewing.",
      send: "Send Message",
      sending: "Sending...",
      sent: "Message sent!",
      sentSub: "The agent will contact you shortly.",
      pageLabel: "Get in touch",
      pageTitle: "We'd love to hear from you",
      pageSub: "Questions about a listing, need a free valuation, or looking to join our team? Reach out — we reply within a business day.",
      phoneLbl: "Phone",
      emailLbl: "Email",
      headOffice: "Head office",
      hours: "Hours",
    },
    mortgage: {
      title: "Mortgage Calculator",
      down: "Down Payment",
      term: "Loan Term",
      years: "years",
      rate: "Interest Rate",
      monthly: "Estimated monthly payment",
    },
    agents: {
      title: "Our Agents",
      label: "Team 21",
      subtitle: "Meet the licensed professionals who make every transaction smooth, transparent and successful.",
      sold: "sold",
      officeSuffix: "office",
      activeListings: "Active listings",
      call: "Call",
      email: "Email",
    },
    offices: {
      title: "Our Offices",
      label: "Nationwide",
      subtitle: "Visit us across Albania. Expert teams ready to help you buy, sell or rent.",
      agents: "agents",
      listings: "listings",
    },
    about: {
      label: "Our Story",
      title: "Building homes and futures since 2010",
      p1: "Brunes Real Estate was founded with a simple mission: to make the Albanian property market more transparent, more professional, and more accessible for everyone.",
      p2: "Today we operate 47 offices across the country, employ over 440 licensed agents, and have helped more than 15,000 families find the place where their story begins.",
      p3: "From the coastline of Sarandë to the mountain resorts of Pogradec, from Tirana's vibrant downtown to quiet suburban streets in Shkodër, our agents know every neighborhood like the back of their hand.",
      valuesTitle: "Our values",
      values: [
        "Transparency. Every listing verified. Every price explained.",
        "Expertise. Continuous training for every agent in our network.",
        "Integrity. Your best interest is always our first priority.",
        "Partnership. We're with you long after the keys change hands.",
      ],
    },
    listProperty: {
      title: "List your property with Brunes",
      sub: "Free valuation, premium placement across our network, expert negotiation. Fill the form below and an agent will call you within 24 hours.",
      fullName: "Full name",
      email: "Email",
      phone: "Phone",
      type: "Property type",
      location: "City & neighborhood",
      tellUs: "Tell us a bit about your property...",
      submit: "Request free valuation",
    },
    footer: {
      tagline: "Albania's trusted real estate platform. Finding homes, building futures since 2010.",
      properties: "Properties",
      apartments: "Apartments",
      villas: "Villas",
      offices: "Offices",
      land: "Land",
      rentals: "Rentals",
      company: "Company",
      aboutUs: "About Us",
      ourAgents: "Our Agents",
      careers: "Careers",
      blog: "Blog",
      contact: "Contact",
      privacy: "Privacy Policy",
      terms: "Terms",
      rights: "All rights reserved.",
    },
    admin: {
      brand: "Brunes Admin",
      welcomeBack: "Welcome back",
      signInHint: "Sign in to manage your properties.",
      email: "Email",
      password: "Password",
      signIn: "Sign in",
      signingIn: "Signing in...",
      invalid: "Invalid credentials",
      adminOnly: "Admin access only",
      defaultHint: "Default admin",
      nav: {
        dashboard: "Dashboard",
        properties: "Properties",
        agents: "Agents",
        offices: "Offices",
        leads: "Leads",
      },
      backToSite: "← Back to site",
      logout: "Logout",
      dashboard: {
        title: "Dashboard",
        welcome: "Welcome back. Here's what's happening.",
        totalProps: "Total Properties",
        active: "active",
        sold: "sold",
        agentsLbl: "Agents",
        agentsSub: "Licensed professionals",
        totalLeads: "Total Leads",
        unread: "unread",
        growth: "Growth",
        thisMonth: "This month",
        recentLeads: "Recent Leads",
        topViewed: "Most Viewed Properties",
        noLeads: "No leads yet.",
        generalInq: "General inquiry",
        viewAll: "View all",
      },
      properties: {
        title: "Properties",
        totalListings: "total listings",
        add: "Add Property",
        property: "Property",
        location: "Location",
        price: "Price",
        status: "Status",
        agent: "Agent",
        views: "Views",
        newTitle: "New Property",
        newSub: "Create a new listing.",
        editTitle: "Edit Property",
      },
      form: {
        back: "Back",
        cancel: "Cancel",
        save: "Save",
        saving: "Saving...",
        update: "Update property",
        create: "Create property",
        basicInfo: "Basic info",
        title: "Title",
        description: "Description",
        type: "Type",
        listing: "Listing",
        status: "Status",
        pricing: "Pricing & size",
        price: "Price (EUR)",
        area: "Area m²",
        rooms: "Rooms",
        bathrooms: "Bathrooms",
        floor: "Floor",
        year: "Year built",
        location: "Location",
        city: "City",
        neighborhood: "Neighborhood",
        address: "Address",
        latitude: "Latitude",
        longitude: "Longitude",
        images: "Images",
        imagesHint: "Upload from your computer or paste an image URL. The first image is the cover.",
        addUrl: "Add URL",
        uploadFiles: "Upload from computer",
        uploading: "Uploading...",
        paste: "Paste image URL",
        upload: "Upload",
        assignment: "Assignment",
        agent: "Agent",
        feature: "Feature on homepage",
      },
      agentsPage: {
        title: "Agents",
        licensed: "licensed agents",
        add: "Add Agent",
      },
      offices: {
        title: "Offices",
        branches: "branches across Albania",
      },
      leads: {
        title: "Leads Inbox",
        sub: "Manage incoming contact-form submissions.",
        noLeads: "No leads yet.",
        showMsg: "Show message",
        hideMsg: "Hide message",
        re: "Re:",
      },
    },
  },
  sq: {
    nav: {
      buy: "Blej",
      rent: "Qira",
      agents: "Agjentët",
      offices: "Zyrat",
      about: "Rreth Nesh",
      contact: "Kontakt",
      listProperty: "Shit Pronën",
      adminLogin: "Admin",
    },
    hero: {
      badge: "Platforma #1 e Pasurive të Paluajtshme në Shqipëri",
      title1: "Gjej vendin ku nis",
      title2: "historia jote",
      subtitle: "Eksploro mijëra shtëpi, apartamente dhe prona investuese të përzgjedhura në lokacionet më të kërkuara të Shqipërisë.",
      search: "Kërko",
      buy: "Blej",
      rent: "Qira",
      anyType: "Çdo lloj",
      maxPrice: "Çmimi maksimal (EUR)",
      location: "Qytet ose lagje",
      stats: {
        listings: "Prona Aktive",
        agents: "Agjentë Ekspertë",
        offices: "Zyra",
        clients: "Klientë të Kënaqur",
      },
    },
    home: {
      destinationsLabel: "Eksploro",
      destinationsTitle: "Destinacione në të gjithë Shqipërinë",
      allProperties: "Të gjitha pronat",
      featuredLabel: "Të Përzgjedhura",
      featuredTitle: "Prona të Veçanta",
      featuredSub: "Lista premium të përzgjedhura nga brokerët tanë kryesorë.",
      viewAll: "Shiko të gjitha",
      whyLabel: "Pse Brunes",
      whyTitle: "Partneri i besuar për udhëtimin tuaj pronësor",
      why: {
        verified: { t: "Lista të Verifikuara", d: "Çdo pronë e kontrolluar nga ekipi ynë i komplajancës." },
        experts: { t: "Agjentë Ekspertë", d: "440+ profesionistë të licencuar në 47 zyra." },
        awards: { t: "Fitues Çmimesh", d: "Rrjeti më i mirë i pasurive të paluajtshme në Shqipëri 2023 & 2024." },
        reach: { t: "Mbulim Kombëtar", d: "Nga resortet bregdetare në qendrën e kryeqytetit." },
      },
      agentsLabel: "Team 21",
      agentsTitle: "Njohu me agjentët tanë më të mirë",
      allAgents: "Të gjithë agjentët",
      ctaTitle: "Gati të listosh pronën tënde?",
      ctaSub: "Arri mijëra blerës seriozë. Vlerësim falas, pozicionim premium, udhëzim ekspert.",
      ctaPrimary: "Listo Falas",
      ctaSecondary: "Fol me një ekspert",
      testimonials: [
        { name: "Arta M.", role: "Bleu një vilë në Sarandë", quote: "Ekipi i Brunes na udhëhoqi në çdo hap. Gjetëm vilën tonë të ëndrrave para bregdetit brenda një muaji." },
        { name: "Luca R.", role: "U zhvendos nga Italia", quote: "Profesionalë, shumëgjuhësh dhe jashtëzakonisht të shpejtë. Nuk do ta imagjinoja zhvendosjen pa ta." },
        { name: "Gent B.", role: "Investitor në prona", quote: "Analizë e detajuar e tregut, lista të verifikuara dhe negocim i fortë. Agjencia ime për çdo marrëveshje." },
      ],
      propsIn: "prona",
    },
    properties: {
      title: "Pronat",
      results: "rezultate",
      showing: "Duke shfaqur",
      of: "nga",
      noResults: "Asnjë pronë e gjetur",
      noResultsSub: "Provo të ndryshosh filtrat.",
      sort: {
        newest: "Më të rejat",
        priceAsc: "Çmimi: nga më i ulët",
        priceDesc: "Çmimi: nga më i larti",
        areaDesc: "Më të mëdhatë",
      },
      filters: {
        title: "Filtrat",
        clear: "Pastro",
        all: "Të gjitha",
        buy: "Blej",
        rent: "Qira",
        type: "Lloji i pronës",
        any: "Çdo",
        city: "Qyteti",
        allCities: "Të gjitha qytetet",
        priceRange: "Gama e çmimit (EUR)",
        min: "Min",
        max: "Max",
        rooms: "Dhoma",
        apply: "Apliko Filtrat",
      },
    },
    propertyCard: {
      featured: "Të zgjedhura",
      forSale: "Në Shitje",
      forRent: "Me Qira",
    },
    propertyDetail: {
      forSale: "Në Shitje",
      forRent: "Me Qira",
      save: "Ruaj",
      share: "Shpërnda",
      about: "Rreth kësaj prone",
      amenities: "Komoditetet",
      location: "Vendndodhja",
      similar: "Prona të ngjashme",
      views: "shikime",
      specs: {
        rooms: "Dhoma",
        baths: "Banjo",
        area: "Sipërfaqja",
        floor: "Kati",
        year: "Viti",
      },
      breadcrumb: { home: "Kreu", properties: "Pronat" },
    },
    contact: {
      formTitle: "Kontakto Agjentin",
      name: "Emri juaj",
      email: "Email",
      phone: "Telefon (opsional)",
      defaultMessage: "Përshëndetje, jam i interesuar për këtë pronë dhe do doja të caktoja një takim.",
      send: "Dërgo Mesazhin",
      sending: "Duke dërguar...",
      sent: "Mesazhi u dërgua!",
      sentSub: "Agjenti do t'ju kontaktojë së shpejti.",
      pageLabel: "Lidhu me ne",
      pageTitle: "Do të donim të dëgjonim nga ju",
      pageSub: "Pyetje për një listë, vlerësim falas, ose dëshironi t'i bashkoheni ekipit? Na shkruani — përgjigjemi brenda një dite pune.",
      phoneLbl: "Telefoni",
      emailLbl: "Email",
      headOffice: "Zyra qendrore",
      hours: "Orari",
    },
    mortgage: {
      title: "Kalkulator Kredie",
      down: "Paradhënia",
      term: "Periudha e kredisë",
      years: "vjet",
      rate: "Norma e Interesit",
      monthly: "Pagesa mujore e vlerësuar",
    },
    agents: {
      title: "Agjentët Tanë",
      label: "Team 21",
      subtitle: "Njohu me profesionistët e licencuar që bëjnë çdo transaksion të thjeshtë, transparent dhe të suksesshëm.",
      sold: "shitur",
      officeSuffix: "zyrë",
      activeListings: "Lista aktive",
      call: "Telefono",
      email: "Email",
    },
    offices: {
      title: "Zyrat Tona",
      label: "Kombëtare",
      subtitle: "Na vizitoni në të gjithë Shqipërinë. Ekipe ekspertësh gati për t'ju ndihmuar të blini, shisni ose jepni me qira.",
      agents: "agjentë",
      listings: "lista",
    },
    about: {
      label: "Historia Jonë",
      title: "Ndërtojmë shtëpi dhe të ardhme që prej vitit 2010",
      p1: "Brunes Real Estate u themelua me një mision të thjeshtë: ta bëjë tregun shqiptar të pasurive të paluajtshme më transparent, më profesional dhe më të arritshëm për të gjithë.",
      p2: "Sot operojmë me 47 zyra në të gjithë vendin, punësojmë mbi 440 agjentë të licencuar dhe kemi ndihmuar më shumë se 15,000 familje të gjejnë vendin ku nis historia e tyre.",
      p3: "Nga bregdeti i Sarandës te resortet malore të Pogradecit, nga qendra e gjallë e Tiranës te rrugët e qeta të Shkodrës, agjentët tanë njohin çdo lagje si pëllëmbën e dorës.",
      valuesTitle: "Vlerat tona",
      values: [
        "Transparencë. Çdo listë e verifikuar. Çdo çmim i shpjeguar.",
        "Ekspertizë. Trajnim i vazhdueshëm për çdo agjent në rrjetin tonë.",
        "Integritet. Interesi juaj është gjithmonë prioriteti ynë i parë.",
        "Partneritet. Jemi me ju shumë kohë pasi çelësat ndërrojnë duar.",
      ],
    },
    listProperty: {
      title: "Listoni pronën tuaj me Brunes",
      sub: "Vlerësim falas, pozicionim premium në rrjetin tonë, negocim ekspert. Plotësoni formularin dhe një agjent do t'ju telefonojë brenda 24 orëve.",
      fullName: "Emri i plotë",
      email: "Email",
      phone: "Telefon",
      type: "Lloji i pronës",
      location: "Qytet & lagje",
      tellUs: "Na tregoni pak për pronën tuaj...",
      submit: "Kërko vlerësim falas",
    },
    footer: {
      tagline: "Platforma e besuar e pasurive të paluajtshme në Shqipëri. Gjejmë shtëpi, ndërtojmë të ardhme që prej vitit 2010.",
      properties: "Pronat",
      apartments: "Apartamente",
      villas: "Vila",
      offices: "Zyra",
      land: "Tokë",
      rentals: "Me qira",
      company: "Kompania",
      aboutUs: "Rreth Nesh",
      ourAgents: "Agjentët Tanë",
      careers: "Karrierë",
      blog: "Blog",
      contact: "Kontakt",
      privacy: "Politika e Privatësisë",
      terms: "Kushtet",
      rights: "Të gjitha të drejtat e rezervuara.",
    },
    admin: {
      brand: "Admin Brunes",
      welcomeBack: "Mirësevini",
      signInHint: "Hyr për të menaxhuar pronat.",
      email: "Email",
      password: "Fjalëkalimi",
      signIn: "Hyr",
      signingIn: "Duke hyrë...",
      invalid: "Kredenciale të pasakta",
      adminOnly: "Vetëm qasje admini",
      defaultHint: "Admini si parazgjedhje",
      nav: {
        dashboard: "Paneli",
        properties: "Pronat",
        agents: "Agjentët",
        offices: "Zyrat",
        leads: "Leads",
      },
      backToSite: "← Kthehu në faqe",
      logout: "Dalja",
      dashboard: {
        title: "Paneli",
        welcome: "Mirësevini. Ja çfarë po ndodh.",
        totalProps: "Prona Gjithsej",
        active: "aktive",
        sold: "shitur",
        agentsLbl: "Agjentë",
        agentsSub: "Profesionistë të licencuar",
        totalLeads: "Leads Gjithsej",
        unread: "pa lexuar",
        growth: "Rritja",
        thisMonth: "Këtë muaj",
        recentLeads: "Leads të fundit",
        topViewed: "Pronat më të shikuara",
        noLeads: "Asnjë lead deri tani.",
        generalInq: "Pyetje e përgjithshme",
        viewAll: "Shiko të gjitha",
      },
      properties: {
        title: "Pronat",
        totalListings: "lista gjithsej",
        add: "Shto Pronë",
        property: "Prona",
        location: "Vendndodhja",
        price: "Çmimi",
        status: "Statusi",
        agent: "Agjenti",
        views: "Shikime",
        newTitle: "Pronë e re",
        newSub: "Krijo një listë të re.",
        editTitle: "Modifiko Pronën",
      },
      form: {
        back: "Kthehu",
        cancel: "Anulo",
        save: "Ruaj",
        saving: "Duke ruajtur...",
        update: "Përditëso pronën",
        create: "Krijo pronën",
        basicInfo: "Informacion bazë",
        title: "Titulli",
        description: "Përshkrimi",
        type: "Lloji",
        listing: "Listimi",
        status: "Statusi",
        pricing: "Çmimi & madhësia",
        price: "Çmimi (EUR)",
        area: "Sipërfaqja m²",
        rooms: "Dhoma",
        bathrooms: "Banjo",
        floor: "Kati",
        year: "Viti i ndërtimit",
        location: "Vendndodhja",
        city: "Qyteti",
        neighborhood: "Lagjja",
        address: "Adresa",
        latitude: "Gjerësia gjeografike",
        longitude: "Gjatësia gjeografike",
        images: "Fotot",
        imagesHint: "Ngarko nga kompjuteri ose ngjit një URL imazhi. Imazhi i parë është kopertina.",
        addUrl: "Shto URL",
        uploadFiles: "Ngarko nga kompjuteri",
        uploading: "Duke ngarkuar...",
        paste: "Ngjit URL imazhi",
        upload: "Ngarko",
        assignment: "Caktimi",
        agent: "Agjenti",
        feature: "Shfaq në faqen kryesore",
      },
      agentsPage: {
        title: "Agjentët",
        licensed: "agjentë të licencuar",
        add: "Shto Agjent",
      },
      offices: {
        title: "Zyrat",
        branches: "degë në të gjithë Shqipërinë",
      },
      leads: {
        title: "Leads Inbox",
        sub: "Menaxho mesazhet nga forma e kontaktit.",
        noLeads: "Asnjë lead deri tani.",
        showMsg: "Shfaq mesazhin",
        hideMsg: "Fsheh mesazhin",
        re: "Re:",
      },
    },
  },
};

export type Locale = keyof typeof dictionaries;
export type Dict = (typeof dictionaries)["en"];
